apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: seldon-deploy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: seldon-deploy-role
subjects:
  - kind: ServiceAccount
    name: {{ include "seldon-deploy.serviceAccountName" . }}
    namespace: '{{ .Release.Namespace }}'
