{{- if .Values.virtualService.create -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "seldon-deploy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "seldon-deploy.name" . }}
    helm.sh/chart: {{ include "seldon-deploy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  {{- with .Values.virtualService.gateways }}
  gateways:
  {{ toYaml . | indent 2 }}
  {{- end }}
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: {{ .Values.virtualService.prefix }}
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ include "seldon-deploy.fullname" . }}
        port:
          number: {{ .Values.service.port }}
{{- end -}}
