ARG VERSION
FROM seldonio/seldon-deploy-operator:$VERSION
LABEL name="Seldon Deploy Operator" \
      vendor="Seldon Technologies" \
      version=$VERSION \
      release=$VERSION \
      summary="Seldon Deploy Operator" \
      description="Helm-based Operator for installing Seldon Deploy."
COPY deployenterpriselicense.txt licenses/license.txt