FROM registry.access.redhat.com/ubi8/ubi
LABEL name="Seldon Kubectl" \
      vendor="Seldon Technologies" \
      version="1.14.3" \
      release="1.14.3" \
      summary="Seldon Kubectl" \
      description="Used within helm chart for delete hook."
ADD https://storage.googleapis.com/kubernetes-release/release/v1.14.3/bin/linux/amd64/kubectl /bin/kubectl
COPY apache2license.txt licenses/license.txt
RUN chmod +x /bin/kubectl
CMD ["sh"]